"""permitir ventas sin cliente

Revision ID: 0d3ae2c1c696
Revises: 9e18307bebe8
Create Date: 2026-09-22 13:10:05.907186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3ae2c1c696'
down_revision: Union[str, Sequence[str], None] = '9e18307bebe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'cliente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
