"""cambiar campos monetarios a numeric

Revision ID: 414185746904
Revises: ea9e0ab5463e
Create Date: 2026-09-10 22:21:09.996805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414185746904'
down_revision: Union[str, Sequence[str], None] = 'ea9e0ab5463e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detalles_venta', 'precio_unitario',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('detalles_venta', 'subtotal',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('productos', 'precio',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('ventas', 'total',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ventas', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    op.alter_column('productos', 'precio',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    op.alter_column('detalles_venta', 'subtotal',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    op.alter_column('detalles_venta', 'precio_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
