"""agregar usuario a ventas

Revision ID: 6fdfb9ee31bf
Revises: 49e65520889a
Create Date: 2026-09-15 15:24:09.603097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fdfb9ee31bf'
down_revision: Union[str, Sequence[str], None] = '49e65520889a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ventas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ventas', type_='foreignkey')
    op.drop_column('ventas', 'usuario_id')
    # ### end Alembic commands ###
