"""agregar activo a productos

Revision ID: 9e18307bebe8
Revises: 6fdfb9ee31bf
Create Date: 2026-09-21 15:05:29.934593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e18307bebe8'
down_revision: Union[str, Sequence[str], None] = '6fdfb9ee31bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'productos',
        sa.Column(
            'activo',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'activo')
    # ### end Alembic commands ###
